# Generated by Django 5.0.4 on 2024-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/onlinebooks')),
                ('language', models.CharField(max_length=50)),
                ('gdrive', models.CharField(max_length=200)),
                ('genre', models.ManyToManyField(to='book.genremodel')),
            ],
        ),
    ]
